"""add otp last sent at to password reset requests

Revision ID: 374f8c961bd8
Revises: a9fe20329ceb
Create Date: 2026-08-13 17:57:42.642990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '374f8c961bd8'
down_revision: Union[str, Sequence[str], None] = 'a9fe20329ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_requests', sa.Column('otp_last_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_workspace_ai_settings_id'), 'workspace_ai_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_ai_settings_id'), table_name='workspace_ai_settings')
    op.drop_column('password_reset_requests', 'otp_last_sent_at')
    # ### end Alembic commands ###
