"""create password reset requests table

Revision ID: a9fe20329ceb
Revises: 34c58541cda3
Create Date: 2026-08-12 16:21:02.573885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fe20329ceb'
down_revision: Union[str, Sequence[str], None] = '34c58541cda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'password_reset_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('otp_hash', sa.String(length=255), nullable=False),
        sa.Column(
            'otp_expires_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column('otp_attempts', sa.Integer(), nullable=False),
        sa.Column('otp_verified', sa.Boolean(), nullable=False),
        sa.Column(
            'reset_token_hash',
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            'reset_token_expires_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column('used', sa.Boolean(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_index(
        op.f('ix_password_reset_requests_id'),
        'password_reset_requests',
        ['id'],
        unique=False,
    )

    op.create_index(
        op.f('ix_password_reset_requests_user_id'),
        'password_reset_requests',
        ['user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_password_reset_requests_user_id'),
        table_name='password_reset_requests',
    )

    op.drop_index(
        op.f('ix_password_reset_requests_id'),
        table_name='password_reset_requests',
    )

    op.drop_table('password_reset_requests')
    # ### end Alembic commands ###
